// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_content_delivery_bucket": "venture-project-bucket-venture",
  "aws_content_delivery_bucket_region": "us-east-1",
  "aws_content_delivery_url": "http://venture-project-bucket-venture.s3-website-us-east-1.amazonaws.com",
  "aws_cognito_identity_pool_id": "us-east-1:8043a41f-4d72-4e33-a230-9a91c6e1aeca",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_dk2kAIw7p",
  "aws_user_pools_web_client_id": "7gtk7t5r024nonojjfcto8g680",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "https://2ilcalho2vebhprvq4m4nvvkzm.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
