// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "venture-project-bucket-venture",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://venture-project-bucket-venture.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:a5050263-39ec-4fb8-9fbc-297f9e3cec6d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0V55cOr1E",
    "aws_user_pools_web_client_id": "1n72vg42i4uqe40of96lk4uvf9",
    "oauth": {}
};


export default awsmobile;
